name: nlpmaps
channels:
  - defaults
dependencies:
  - gensim
  - jupyter
  - keras
  - nltk
  - notebook
  - numpy
  - openpyxl
  - pandas
  - pip
  - python
  - requests
  - scikit-learn
  - scipy
  - tensorflow
  - tqdm
  - gensim
  - tqdm
  - tensorflow_hub
  - pip:
      - datasets
      - fasttext
      - nose2
      - optuna
      - tf-models-official
      - spacy
      - wget