name: nlpmaps
channels:
  - defaults
dependencies:
  - pip:
      - tensorflow-text
      - tf-models-official
      - gensim
      - numpy
      - pandas
      - scikit-learn
      - matplotlib
      - seaborn
      - xgboost
      - nltk
      - spacy
      - keras
      - tensorflow_hub
      - tensorflow
      - datasets
      - requests
      - unittest
      - fasttext
      - optuna
